trigger:
  branches:
    include:
      - main

variables:
  imageName: 'aks-flask-prod-env-app'
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: 'Build and Push Image'
    jobs:
      - job: Build
        displayName: 'Build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'FlaskAppACR'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: 'app/Dockerfile'
              tags: |
                latest
                $(tag)

  - stage: Deploy
    displayName: 'Deploy to AKS'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-aks'
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials --resource-group aks-flask-prod-env-rg --name aks-flask-prod-env-cluster
                kubectl apply -f k8s/
